package com.eng.sentence.domain.models;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Base64;
import java.sql.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Set;

import javax.persistence.*;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Subselect;
import org.hibernate.annotations.Synchronize;
import org.springframework.validation.annotation.Validated;
import com.eng.sentence.domain.utils.ByteConverter;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.format.annotation.DateTimeFormat;
import com.eng.sentence.domain.utils.StringConverter;

@Entity
@Table(name = "subject_sentence")
public class SubjectSentence implements java.io.Serializable {
	/*
	* Added insertable=false and updatable=false.
	* This means that this column will not be used in INSERT or UPDATE statements,
	* because its value is automatically generated by the database.
	*/
	@Id
	@GeneratedValue(generator = "UUID")
	@GenericGenerator(
	name = "UUID",
	strategy = "org.hibernate.id.UUIDGenerator"
	)
	@Column(name = "subject_sentence_id", updatable = false, insertable = false, nullable = false)
	@JsonProperty("subject_sentence_id")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String subject_sentence_id;
	@Column(name = "situation")
	@JsonProperty("situation")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String situation;
	@Column(name = "event")
	@JsonProperty("event")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String event;
	@Column(name = "sentence_type")
	@JsonProperty("sentence_type")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String sentence_type;
	@Column(name = "article_01")
	@JsonProperty("article_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String article_01;
	@Column(name = "subject_01")
	@JsonProperty("subject_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String subject_01;
	@Column(name = "conjunction_01")
	@JsonProperty("conjunction_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String conjunction_01;
	@Column(name = "adverb_01")
	@JsonProperty("adverb_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String adverb_01;
	@Column(name = "auxiliary_verb_01")
	@JsonProperty("auxiliary_verb_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String auxiliary_verb_01;
	@Column(name = "verb_01")
	@JsonProperty("verb_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String verb_01;
	@Column(name = "infinitive_01")
	@JsonProperty("infinitive_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String infinitive_01;
	@Column(name = "conjunction_02")
	@JsonProperty("conjunction_02")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String conjunction_02;
	@Column(name = "adverb_02")
	@JsonProperty("adverb_02")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String adverb_02;
	@Column(name = "preposition_01")
	@JsonProperty("preposition_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String preposition_01;
	@Column(name = "pronoun_01")
	@JsonProperty("pronoun_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String pronoun_01;
	@Column(name = "article_02")
	@JsonProperty("article_02")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String article_02;
	@Column(name = "adjective_01")
	@JsonProperty("adjective_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String adjective_01;
	@Column(name = "noun_01")
	@JsonProperty("noun_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String noun_01;
	@Column(name = "noun_phase_01")
	@JsonProperty("noun_phase_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String noun_phase_01;
	@Column(name = "gerund_01")
	@JsonProperty("gerund_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String gerund_01;
	@Column(name = "preposition_02")
	@JsonProperty("preposition_02")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String preposition_02;
	@Column(name = "clause_01")
	@JsonProperty("clause_01")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String clause_01;
	@Column(name = "full_sentence")
	@JsonProperty("full_sentence")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String full_sentence;
	@Column(name = "traditional_chinese")
	@JsonProperty("traditional_chinese")
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	private String traditional_chinese;
	public SubjectSentence() {
	}
	public SubjectSentence(
	String subject_sentence_id
	,
	String situation
	,
	String event
	,
	String sentence_type
	,
	String article_01
	,
	String subject_01
	,
	String conjunction_01
	,
	String adverb_01
	,
	String auxiliary_verb_01
	,
	String verb_01
	,
	String infinitive_01
	,
	String conjunction_02
	,
	String adverb_02
	,
	String preposition_01
	,
	String pronoun_01
	,
	String article_02
	,
	String adjective_01
	,
	String noun_01
	,
	String noun_phase_01
	,
	String gerund_01
	,
	String preposition_02
	,
	String clause_01
	,
	String full_sentence
	,
	String traditional_chinese
	) {
		this.subject_sentence_id = subject_sentence_id;
		this.situation = situation;
		this.event = event;
		this.sentence_type = sentence_type;
		this.article_01 = article_01;
		this.subject_01 = subject_01;
		this.conjunction_01 = conjunction_01;
		this.adverb_01 = adverb_01;
		this.auxiliary_verb_01 = auxiliary_verb_01;
		this.verb_01 = verb_01;
		this.infinitive_01 = infinitive_01;
		this.conjunction_02 = conjunction_02;
		this.adverb_02 = adverb_02;
		this.preposition_01 = preposition_01;
		this.pronoun_01 = pronoun_01;
		this.article_02 = article_02;
		this.adjective_01 = adjective_01;
		this.noun_01 = noun_01;
		this.noun_phase_01 = noun_phase_01;
		this.gerund_01 = gerund_01;
		this.preposition_02 = preposition_02;
		this.clause_01 = clause_01;
		this.full_sentence = full_sentence;
		this.traditional_chinese = traditional_chinese;
		this.Init();
	}
	public void Init() {
	}
	public void setSubjectSentenceId(String subject_sentence_id) {
		this.subject_sentence_id = subject_sentence_id;
	}
	public String getSubjectSentenceId() {
		return this.subject_sentence_id;
	}
	public void setSituation(String situation) {
		this.situation = situation;
	}
	public String getSituation() {
		return this.situation;
	}
	public void setEvent(String event) {
		this.event = event;
	}
	public String getEvent() {
		return this.event;
	}
	public void setSentenceType(String sentence_type) {
		this.sentence_type = sentence_type;
	}
	public String getSentenceType() {
		return this.sentence_type;
	}
	public void setArticle01(String article_01) {
		this.article_01 = article_01;
	}
	public String getArticle01() {
		return this.article_01;
	}
	public void setSubject01(String subject_01) {
		this.subject_01 = subject_01;
	}
	public String getSubject01() {
		return this.subject_01;
	}
	public void setConjunction01(String conjunction_01) {
		this.conjunction_01 = conjunction_01;
	}
	public String getConjunction01() {
		return this.conjunction_01;
	}
	public void setAdverb01(String adverb_01) {
		this.adverb_01 = adverb_01;
	}
	public String getAdverb01() {
		return this.adverb_01;
	}
	public void setAuxiliaryVerb01(String auxiliary_verb_01) {
		this.auxiliary_verb_01 = auxiliary_verb_01;
	}
	public String getAuxiliaryVerb01() {
		return this.auxiliary_verb_01;
	}
	public void setVerb01(String verb_01) {
		this.verb_01 = verb_01;
	}
	public String getVerb01() {
		return this.verb_01;
	}
	public void setInfinitive01(String infinitive_01) {
		this.infinitive_01 = infinitive_01;
	}
	public String getInfinitive01() {
		return this.infinitive_01;
	}
	public void setConjunction02(String conjunction_02) {
		this.conjunction_02 = conjunction_02;
	}
	public String getConjunction02() {
		return this.conjunction_02;
	}
	public void setAdverb02(String adverb_02) {
		this.adverb_02 = adverb_02;
	}
	public String getAdverb02() {
		return this.adverb_02;
	}
	public void setPreposition01(String preposition_01) {
		this.preposition_01 = preposition_01;
	}
	public String getPreposition01() {
		return this.preposition_01;
	}
	public void setPronoun01(String pronoun_01) {
		this.pronoun_01 = pronoun_01;
	}
	public String getPronoun01() {
		return this.pronoun_01;
	}
	public void setArticle02(String article_02) {
		this.article_02 = article_02;
	}
	public String getArticle02() {
		return this.article_02;
	}
	public void setAdjective01(String adjective_01) {
		this.adjective_01 = adjective_01;
	}
	public String getAdjective01() {
		return this.adjective_01;
	}
	public void setNoun01(String noun_01) {
		this.noun_01 = noun_01;
	}
	public String getNoun01() {
		return this.noun_01;
	}
	public void setNounPhase01(String noun_phase_01) {
		this.noun_phase_01 = noun_phase_01;
	}
	public String getNounPhase01() {
		return this.noun_phase_01;
	}
	public void setGerund01(String gerund_01) {
		this.gerund_01 = gerund_01;
	}
	public String getGerund01() {
		return this.gerund_01;
	}
	public void setPreposition02(String preposition_02) {
		this.preposition_02 = preposition_02;
	}
	public String getPreposition02() {
		return this.preposition_02;
	}
	public void setClause01(String clause_01) {
		this.clause_01 = clause_01;
	}
	public String getClause01() {
		return this.clause_01;
	}
	public void setFullSentence(String full_sentence) {
		this.full_sentence = full_sentence;
	}
	public String getFullSentence() {
		return this.full_sentence;
	}
	public void setTraditionalChinese(String traditional_chinese) {
		this.traditional_chinese = traditional_chinese;
	}
	public String getTraditionalChinese() {
		return this.traditional_chinese;
	}
	@Override
	public String toString() {
		return "SubjectSentence [" +
		"subject_sentence_id"+
		"=" + StringConverter.toString(this.subject_sentence_id)+
		","+
		"situation"+
		"=" + StringConverter.toString(this.situation)+
		","+
		"event"+
		"=" + StringConverter.toString(this.event)+
		","+
		"sentence_type"+
		"=" + StringConverter.toString(this.sentence_type)+
		","+
		"article_01"+
		"=" + StringConverter.toString(this.article_01)+
		","+
		"subject_01"+
		"=" + StringConverter.toString(this.subject_01)+
		","+
		"conjunction_01"+
		"=" + StringConverter.toString(this.conjunction_01)+
		","+
		"adverb_01"+
		"=" + StringConverter.toString(this.adverb_01)+
		","+
		"auxiliary_verb_01"+
		"=" + StringConverter.toString(this.auxiliary_verb_01)+
		","+
		"verb_01"+
		"=" + StringConverter.toString(this.verb_01)+
		","+
		"infinitive_01"+
		"=" + StringConverter.toString(this.infinitive_01)+
		","+
		"conjunction_02"+
		"=" + StringConverter.toString(this.conjunction_02)+
		","+
		"adverb_02"+
		"=" + StringConverter.toString(this.adverb_02)+
		","+
		"preposition_01"+
		"=" + StringConverter.toString(this.preposition_01)+
		","+
		"pronoun_01"+
		"=" + StringConverter.toString(this.pronoun_01)+
		","+
		"article_02"+
		"=" + StringConverter.toString(this.article_02)+
		","+
		"adjective_01"+
		"=" + StringConverter.toString(this.adjective_01)+
		","+
		"noun_01"+
		"=" + StringConverter.toString(this.noun_01)+
		","+
		"noun_phase_01"+
		"=" + StringConverter.toString(this.noun_phase_01)+
		","+
		"gerund_01"+
		"=" + StringConverter.toString(this.gerund_01)+
		","+
		"preposition_02"+
		"=" + StringConverter.toString(this.preposition_02)+
		","+
		"clause_01"+
		"=" + StringConverter.toString(this.clause_01)+
		","+
		"full_sentence"+
		"=" + StringConverter.toString(this.full_sentence)+
		","+
		"traditional_chinese"+
		"=" + StringConverter.toString(this.traditional_chinese)+
		"]";
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj){
			return true;
		}
		if (obj == null){
			return false;
		}
		if (getClass() != obj.getClass()){
			return false;
		}
		SubjectSentence other = (SubjectSentence) obj;
		return Objects.equals(this.subject_sentence_id, other.subject_sentence_id)
			&& Objects.equals(this.situation, other.situation)
			&& Objects.equals(this.event, other.event)
			&& Objects.equals(this.sentence_type, other.sentence_type)
			&& Objects.equals(this.article_01, other.article_01)
			&& Objects.equals(this.subject_01, other.subject_01)
			&& Objects.equals(this.conjunction_01, other.conjunction_01)
			&& Objects.equals(this.adverb_01, other.adverb_01)
			&& Objects.equals(this.auxiliary_verb_01, other.auxiliary_verb_01)
			&& Objects.equals(this.verb_01, other.verb_01)
			&& Objects.equals(this.infinitive_01, other.infinitive_01)
			&& Objects.equals(this.conjunction_02, other.conjunction_02)
			&& Objects.equals(this.adverb_02, other.adverb_02)
			&& Objects.equals(this.preposition_01, other.preposition_01)
			&& Objects.equals(this.pronoun_01, other.pronoun_01)
			&& Objects.equals(this.article_02, other.article_02)
			&& Objects.equals(this.adjective_01, other.adjective_01)
			&& Objects.equals(this.noun_01, other.noun_01)
			&& Objects.equals(this.noun_phase_01, other.noun_phase_01)
			&& Objects.equals(this.gerund_01, other.gerund_01)
			&& Objects.equals(this.preposition_02, other.preposition_02)
			&& Objects.equals(this.clause_01, other.clause_01)
			&& Objects.equals(this.full_sentence, other.full_sentence)
			&& Objects.equals(this.traditional_chinese, other.traditional_chinese);
	}
}